### PR TITLE
Upgrade Django version to 1.8

### PR DESCRIPTION
**Pull request by muzaffaryousaf**
https://openedx.atlassian.net/browse/TNL-2825

### CODE REVIEW

**Comment by muzaffaryousaf** [comment]
@mulby Any suggestions/feedback or testing strategy for this PR since you're top contributor of this repo. Thanks.

**Comment by muzaffaryousaf** [comment]
@symbolist @macdiesel @wedaly Would you mind to give it a look ? Thanks.

**Comment by macdiesel** [comment]
We should bump the library version number.

**Comment by mulby** [comment]
Agreed we should bump the version number. Once that's done :+1:

**Comment by muzaffaryousaf** [comment]
@macdiesel @mulby Sure thing. Thanks.

**Comment by symbolist** [comment]
:+1:

**Pull request merged**
